version: '3'

services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./www/html/:/var/www/html/

  php:
    image: php7.0-fpm
    build: ./php/
    container_name: php-container
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - ./www/html/:/var/www/html/


  mysql:
    image: mysql:5.7
    container_name: mysql-container
    volumes_from:
      - mysql-data
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=deneme
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password

  mysql-data:
    image: mysql:5.7
    container_name: mysql-data-container
    volumes:
      - /var/lib/mysql
    command: "true"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret


